-- Esquema PostgreSQL de Purgito. Generado desde la SQLite de producción
-- (misma forma de columnas) y luego mantenido a mano. Idempotente: todo es
-- IF NOT EXISTS, se aplica en cada arranque (db.init_db).

-- Los timestamps de Purgito son TEXT 'YYYY-MM-DD HH24:MI:SS' en UTC (formato
-- heredado de SQLite, que el código compara como string). utc_now() es el "ahora"
-- en ese formato; los DEFAULT de abajo lo inlinean.
CREATE OR REPLACE FUNCTION utc_now() RETURNS text
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$ SELECT to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS') $$;

-- t + delta, en el mismo formato texto, o NULL si `t` no es una fecha válida (o
-- la suma se sale de rango). SQLite devolvía NULL con una fecha malformada y la
-- fila simplemente no cumplía la condición; el cast `::timestamp` de PostgreSQL
-- en cambio aborta la query ENTERA (y con ella a todo el scheduler). Esta
-- función conserva el comportamiento de SQLite: una fila inválida da NULL y las
-- demás siguen. Las queries de vencimiento deciden qué hacer con ese NULL.
-- Un año de 5 dígitos (la suma cruzó el 9999) también es NULL: como texto
-- "10000-01-01" ordenaría ANTES que "2026-..." y parecería vencido.
CREATE OR REPLACE FUNCTION utc_text_plus(t text, delta interval) RETURNS text
    LANGUAGE plpgsql STABLE PARALLEL SAFE
    AS $$
DECLARE
    v text;
BEGIN
    v := to_char(t::timestamp + delta, 'YYYY-MM-DD HH24:MI:SS');
    IF length(v) <> 19 THEN
        RETURN NULL;
    END IF;
    RETURN v;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS settings (
    guild_id BIGINT,
    chat_mode_enabled BIGINT NOT NULL DEFAULT 1,
    chat_channel_id BIGINT,
    mention_rate_limit BIGINT NOT NULL DEFAULT 10,
    locale TEXT,
    updates_channel_id BIGINT,
    auto_generate_every BIGINT NOT NULL DEFAULT 15,
    auto_generate_probability DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    reaction_probability DOUBLE PRECISION NOT NULL DEFAULT 0.05,
    gif_response_probability DOUBLE PRECISION NOT NULL DEFAULT 0.45,
    frase_probability DOUBLE PRECISION NOT NULL DEFAULT 0.05,
    custom_prefix TEXT,
    manager_role_id BIGINT,
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS corpus_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id),
    UNIQUE (guild_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_corpus_messages_guild ON corpus_messages(guild_id);
CREATE INDEX IF NOT EXISTS idx_corpus_messages_guild_channel ON corpus_messages(guild_id, channel_id);
CREATE TABLE IF NOT EXISTS corpus_gifs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    media_url TEXT,
    fail_count BIGINT NOT NULL DEFAULT 0,
    last_health_check TEXT,
    checked_at TEXT,
    dead_streak BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT,
    resolve_attempts BIGINT NOT NULL DEFAULT 0,
    resolve_retry_at TEXT,
    PRIMARY KEY (id),
    UNIQUE (guild_id, url)
);

CREATE TABLE IF NOT EXISTS gif_objects (
    content_hash TEXT,
    r2_key TEXT NOT NULL,
    ref_count BIGINT NOT NULL DEFAULT 0,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    phash TEXT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    frame_count BIGINT,
    width BIGINT,
    height BIGINT,
    duration_ms BIGINT,
    phashes TEXT,
    PRIMARY KEY (content_hash)
);

-- content_hash o url puede ser NULL (tenor/giphy no tienen hash; legacy sin
-- hash). SQLite toleraba NULL dentro de la PRIMARY KEY; PostgreSQL no, así que
-- la unicidad va por un índice sobre COALESCE en vez de PK.
CREATE TABLE IF NOT EXISTS gif_blocklist (
    guild_id BIGINT NOT NULL,
    content_hash TEXT,
    url TEXT,
    blocked_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_gif_blocklist
    ON gif_blocklist (guild_id, COALESCE(content_hash, ''), COALESCE(url, ''));
CREATE INDEX IF NOT EXISTS idx_gif_blocklist_guild_hash ON gif_blocklist (guild_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_gif_blocklist_guild_url ON gif_blocklist (guild_id, url);

CREATE TABLE IF NOT EXISTS youtube_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    youtube_channel_id TEXT NOT NULL,
    youtube_channel_name TEXT NOT NULL,
    last_video_id TEXT,
    discord_channel_id BIGINT NOT NULL,
    mention_role_id BIGINT,
    last_error TEXT,
    PRIMARY KEY (id),
    UNIQUE (guild_id, youtube_channel_id)
);

CREATE TABLE IF NOT EXISTS rss_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    feed_url TEXT NOT NULL,
    feed_title TEXT NOT NULL,
    last_item_id TEXT,
    discord_channel_id BIGINT NOT NULL,
    mention_role_id BIGINT,
    last_error TEXT,
    PRIMARY KEY (id),
    UNIQUE (guild_id, feed_url)
);

CREATE TABLE IF NOT EXISTS user_corpus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    author_name TEXT NOT NULL,
    message_id BIGINT,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    channel_id BIGINT,
    PRIMARY KEY (id),
    UNIQUE (guild_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_user_corpus_guild_author ON user_corpus(guild_id, author_id);
CREATE TABLE IF NOT EXISTS ignored_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS meme_schedule (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    interval_minutes BIGINT NOT NULL DEFAULT 180,
    last_posted_at TEXT,
    last_error TEXT,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS channel_webhooks (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    webhook_id BIGINT NOT NULL,
    webhook_token TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS scheduled_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    mode TEXT NOT NULL,
    interval_minutes BIGINT,
    hour BIGINT,
    minute BIGINT,
    last_sent_at TEXT,
    created_by BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    embed_json TEXT DEFAULT NULL,
    content_mode TEXT NOT NULL DEFAULT 'classic_embed',
    delete_after_seconds BIGINT,
    weekdays TEXT,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_scheduled_announcements_guild ON scheduled_announcements(guild_id);
CREATE TABLE IF NOT EXISTS embed_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    embed_json TEXT NOT NULL,
    content_mode TEXT NOT NULL DEFAULT 'classic_embed',
    message TEXT DEFAULT NULL,
    created_at TEXT DEFAULT utc_now(),
    updated_at TEXT DEFAULT utc_now(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_embed_templates_guild ON embed_templates(guild_id);
CREATE TABLE IF NOT EXISTS embed_uploaded_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id),
    UNIQUE (guild_id, url)
);

CREATE INDEX IF NOT EXISTS idx_embed_uploaded_images_guild ON embed_uploaded_images(guild_id);
CREATE TABLE IF NOT EXISTS layout_button_actions (
    custom_id TEXT,
    guild_id BIGINT NOT NULL,
    action_type TEXT NOT NULL,
    action_data TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (custom_id)
);

CREATE INDEX IF NOT EXISTS idx_layout_button_actions_guild ON layout_button_actions(guild_id);
CREATE TABLE IF NOT EXISTS corpus_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id),
    UNIQUE (guild_id, url)
);

CREATE TABLE IF NOT EXISTS frases_especiales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name TEXT NOT NULL,
    frase TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    pack_id BIGINT,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_frases_especiales_guild ON frases_especiales(guild_id);
CREATE TABLE IF NOT EXISTS frase_allowed_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS frase_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id),
    UNIQUE (guild_id, name)
);

CREATE TABLE IF NOT EXISTS frase_pack_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    pack_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS reaction_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    emoji_text TEXT NOT NULL,
    is_custom BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id),
    UNIQUE (guild_id, emoji_text)
);

CREATE INDEX IF NOT EXISTS idx_reaction_pool_guild ON reaction_pool(guild_id);
CREATE TABLE IF NOT EXISTS chat_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS spontaneous_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS mention_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS channel_settings (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    auto_generate_every BIGINT,
    auto_generate_probability DOUBLE PRECISION,
    reaction_probability DOUBLE PRECISION,
    gif_response_probability DOUBLE PRECISION,
    mention_rate_limit BIGINT,
    frase_probability DOUBLE PRECISION,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS channel_triggers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    match_type TEXT NOT NULL,
    pattern TEXT NOT NULL,
    action TEXT NOT NULL,
    pack_id BIGINT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_channel_triggers_channel ON channel_triggers(guild_id, channel_id);
CREATE TABLE IF NOT EXISTS corpus_allowed_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS mention_rate_limit_exempt_roles (
    guild_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, role_id)
);

CREATE TABLE IF NOT EXISTS mention_rate_limit_exempt_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS excluded_users (
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    exclude_interaction BIGINT NOT NULL DEFAULT 0,
    exclude_learning BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (guild_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_excluded_users_guild ON excluded_users(guild_id);
CREATE TABLE IF NOT EXISTS applied_migrations (
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (guild_id, name)
);

CREATE TABLE IF NOT EXISTS guild_counters (
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    "count" BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (guild_id, name)
);

CREATE TABLE IF NOT EXISTS guild_bot_style (
    guild_id BIGINT,
    nick TEXT,
    avatar_url TEXT,
    banner_url TEXT,
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS premium_guilds (
    guild_id BIGINT,
    added_at TEXT NOT NULL,
    note TEXT,
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS premium_event_watermark (
    guild_id BIGINT,
    last_event_at TEXT NOT NULL,
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS premium_subscriptions (
    guild_id BIGINT,
    subscription_id TEXT,
    customer_id TEXT,
    purchaser_user_id TEXT,
    product_id TEXT,
    status TEXT,
    current_period_start TEXT,
    current_period_end TEXT,
    trial_start TEXT,
    trial_end TEXT,
    cancel_at_period_end BIGINT,
    canceled_at TEXT,
    event_at TEXT,
    updated_at TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS guild_departures (
    guild_id BIGINT,
    left_at TEXT NOT NULL,
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS channel_refeed_status (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    newest_message_id BIGINT,
    oldest_message_id BIGINT,
    backfill_complete BIGINT NOT NULL DEFAULT 0,
    last_refed_at TEXT,
    PRIMARY KEY (guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS guild_auto_refeed (
    guild_id BIGINT,
    triggered_at TEXT NOT NULL,
    completed_at TEXT,
    welcome_channel_id BIGINT,
    PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS shared_embeds (
    share_id TEXT,
    payload TEXT NOT NULL,
    created_guild_id BIGINT,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    PRIMARY KEY (share_id)
);

CREATE TABLE IF NOT EXISTS pending_message_deletions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    channel_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    delete_at TEXT NOT NULL,
    created_at TEXT DEFAULT utc_now(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pending_message_deletions_delete_at ON pending_message_deletions(delete_at);
CREATE TABLE IF NOT EXISTS lifecycle_state (
    id BIGINT,
    clean_shutdown BIGINT NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    CHECK (id = 1),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT,
    created_at TEXT NOT NULL DEFAULT utc_now(),
    previous_detail TEXT,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_audit_log_guild ON audit_log(guild_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log(guild_id, user_id, id DESC);
CREATE TABLE IF NOT EXISTS revoked_sessions (
    sid TEXT,
    revoked_at TEXT NOT NULL,
    PRIMARY KEY (sid)
);

CREATE TABLE IF NOT EXISTS server_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    enabled BIGINT NOT NULL DEFAULT 0,
    channel_id BIGINT,
    content_mode TEXT NOT NULL DEFAULT 'plain_text',
    message TEXT,
    embed_json TEXT,
    template_id BIGINT DEFAULT NULL,
    created_at TEXT DEFAULT utc_now(),
    updated_at TEXT DEFAULT utc_now(),
    last_error TEXT DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (guild_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_server_events_guild ON server_events(guild_id);
CREATE TABLE IF NOT EXISTS member_boost_records (
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    premium_since TEXT NOT NULL,
    created_at TEXT DEFAULT utc_now(),
    PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE IF NOT EXISTS twitch_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    guild_id BIGINT NOT NULL,
    twitch_user_id TEXT NOT NULL,
    twitch_login TEXT NOT NULL,
    last_stream_id TEXT,
    discord_channel_id BIGINT NOT NULL,
    mention_role_id BIGINT,
    last_error TEXT,
    PRIMARY KEY (id),
    UNIQUE (guild_id, twitch_user_id)
);

CREATE TABLE IF NOT EXISTS gif_senders (
    gif_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    channel_id BIGINT,
    message_id BIGINT,
    send_count BIGINT NOT NULL DEFAULT 1,
    first_seen TEXT NOT NULL DEFAULT utc_now(),
    last_seen TEXT NOT NULL DEFAULT utc_now(),
    PRIMARY KEY (gif_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_gif_senders_guild_user ON gif_senders(guild_id, user_id);

-- Lápidas de /borrar_mis_datos: lo MÍNIMO para volver a borrar a un usuario si se
-- restaura un backup anterior a su borrado. Solo el id, sin contenido, sin
-- servidores (el borrado es global) y con caducidad (DELETION_TOMBSTONE_RETENTION_DAYS,
-- un poco más que la vida de los backups). Ver docs/PRIVACY.md.
CREATE TABLE IF NOT EXISTS deleted_user_tombstones (
    user_id BIGINT NOT NULL,
    deleted_at TEXT NOT NULL DEFAULT utc_now(),
    expires_at TEXT NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE INDEX IF NOT EXISTS idx_deleted_user_tombstones_expires ON deleted_user_tombstones(expires_at);
